{
  Zenburn = { "jnurmine/Zenburn" },
  aniseed = { "Olical/aniseed" },
  ["cmp-nvim-lsp"] = { "hrsh7th/cmp-nvim-lsp" },
  ["cmp-path"] = { "hrsh7th/cmp-path" },
  ["cmp-vsnip"] = { "hrsh7th/cmp-vsnip" },
  ["colibri.vim"] = { "archseer/colibri.vim" },
  conjure = { "Olical/conjure" },
  delimitMate = { "Raimondi/delimitMate",
    config = "config.delimitMate"
  },
  everforest = { "sainnhe/everforest" },
  ["friendly-snippets"] = { "rafamadriz/friendly-snippets" },
  gruvbox = { "morhetz/gruvbox" },
  ["impatient.nvim"] = { "lewis6991/impatient.nvim" },
  ["indent-blankline.nvim"] = { "lukas-reineke/indent-blankline.nvim" },
  ["lualine.nvim"] = { "nvim-lualine/lualine.nvim" },
  ["markdown-preview.nvim"] = { "iamcco/markdown-preview.nvim" },
  molokai = { "tomasr/molokai" },
  nerdcommenter = { "preservim/nerdcommenter" },
  ["night-owl.vim"] = { "haishanh/night-owl.vim" },
  ["nord-vim"] = { "arcticicestudio/nord-vim" },
  ["nvim-cmp"] = { "hrsh7th/nvim-cmp" },
  ["nvim-lsp-installer"] = { "williamboman/nvim-lsp-installer" },
  ["nvim-lspconfig"] = { "neovim/nvim-lspconfig" },
  ["nvim-luapad"] = { "rafcamlet/nvim-luapad",
    config = "config.nvim-luapad"
  },
  ["nvim-treesitter"] = { "nvim-treesitter/nvim-treesitter",
    config = "config.nvim-treesitter"
  },
  ["nvim-treesitter-textobjects"] = { "nvim-treesitter/nvim-treesitter-textobjects",
    config = "config.nvim-treesitter-textobjects"
  },
  ["nvim-web-devicons"] = { "kyazdani42/nvim-web-devicons" },
  ["oceanic-next"] = { "mhartington/oceanic-next" },
  ["packer.nvim"] = { "wbthomason/packer.nvim" },
  ["palenight.vim"] = { "drewtempelmeyer/palenight.vim" },
  ["papercolor-theme"] = { "NLKNguyen/papercolor-theme" },
  ["persistence.nvim"] = { "folke/persistence.nvim",
    config = "config.persistence_nvim"
  },
  ["plenary.nvim"] = { "nvim-lua/plenary.nvim" },
  spaceduck = { "pineapplegiant/spaceduck" },
  tabular = { "godlygeek/tabular" },
  tagbar = { "preservim/tagbar",
    config = "config.tagbar"
  },
  ["telescope-file-browser.nvim"] = { "nvim-telescope/telescope-file-browser.nvim" },
  ["telescope-fzf-native.nvim"] = { "nvim-telescope/telescope-fzf-native.nvim" },
  ["telescope-project.nvim"] = { "nvim-telescope/telescope-project.nvim" },
  ["telescope-vim-bookmarks.nvim"] = { "tom-anders/telescope-vim-bookmarks.nvim" },
  ["telescope.nvim"] = { "nvim-telescope/telescope.nvim" },
  ["trouble.nvim"] = { "folke/trouble.nvim" },
  ["twilight.nvim"] = { "folke/twilight.nvim" },
  undotree = { "mbbill/undotree",
    config = "config.undotree"
  },
  vim = { "dracula/vim" },
  ["vim-atom-dark"] = { "gosukiwi/vim-atom-dark" },
  ["vim-bookmarks"] = { "MattesGroeger/vim-bookmarks",
    config = "config.vim-bookmarks"
  },
  ["vim-devicons"] = { "ryanoasis/vim-devicons" },
  ["vim-fugitive"] = { "tpope/vim-fugitive",
    config = "config.vim-fugitive"
  },
  ["vim-markdown"] = { "plasticboy/vim-markdown" },
  ["vim-rhubarb"] = { "tpope/vim-rhubarb" },
  ["vim-surround"] = { "tpope/vim-surround" },
  ["vim-vsnip"] = { "hrsh7th/vim-vsnip",
    config = "config.vim-vsnip"
  },
  ["vim-vsnip-integ"] = { "hrsh7th/vim-vsnip-integ" },
  vimpeccable = { "svermeulen/vimpeccable" },
  vimspector = { "puremourning/vimspector",
    config = "config.vimspector"
  },
  ["which-key.nvim"] = { "folke/which-key.nvim" },
  ["zen-mode.nvim"] = { "folke/zen-mode.nvim",
    config = "config.zen-mode_nvim"
  }
}