local tp = require('core.templates')
kbd.new('templatenewsplit', 'n', '<leader>&ts', tp.new, false, 'Edit a new template in split'):enable()
kbd.new('templatenewvsplit', 'n', '<leader>&tv', tp.new, false, 'Edit a new template in vsplit'):enable()
kbd.new('templatenewfloat', 'n', '<leader>&tf', tp.new, false, 'Edit a new template in floating win'):enable()
kbd.new('templateenable', 'n', '<leader>&te', function ()
    tp.load()
    tp.enable()
end, false, 'Enable template insertion'):enable()
