local utils = require('modules.utils.common')
local tutils = require('modules.utils.table')
local param = require('modules.utils.param')
local func = require('modules.utils.function')
local strutils = require('modules.utils.string')
local mod = require('modules.utils.class')
local dict = require('modules.utils.type.table')
local fn = require('modules.utils.type.callable')
local file = require('modules.utils.type.file')
local str = require('modules.utils.type.string')

utils.globalize(utils)
utils.globalize(tutils)
utils.globalize(param)
utils.globalize(strutils)
utils.globalize(func)

utils.add_global(mod, 'mod')
utils.add_global(dict, 'dict')
utils.add_global(fn, 'func')
utils.add_global(str, 'str')
utils.add_global(file, 'file')
