kbd.new('gitstage', 'n', '<leader>gs', ':Git stage<CR>', false, 'Stage current file'):enable()
kbd.new('gitpush', 'n', '<leader>gp', ':Git push<CR>', false, 'Push changes to remote'):enable()
kbd.new('gitadd', 'n', '<leader>ga', ':Git add<CR>', false, 'Git init in dir'):enable()
kbd.new('gitcommit', 'n', '<leader>gc', ':Git commit<CR>', false, 'Commit changes'):enable()
kbd.new('gitpull', 'n', '<leader>gP', ':Git pull<CR>', false, 'Pull changes'):enable()
