kbd.new('n', '<leader>gg', ':Git<CR>', false, 'Open Fugitive'):enable()
kbd.new('n', '<leader>gs', ':Git stage<CR>', false, 'Stage current file'):enable()
kbd.new('n', '<leader>gp', ':Git push<CR>', false, 'Push changes to remote'):enable()
kbd.new('n', '<leader>ga', ':Git add<CR>', false, 'Git init in dir'):enable()
kbd.new('n', '<leader>gc', ':Git commit<CR>', false, 'Commit changes'):enable()
kbd.new('n', '<leader>gP', ':Git pull<CR>', false, 'Pull changes'):enable()
